version: '3'

services:

  devops_exam_db: #Имя сервиса
    container_name: devops_exam_db #Имя с которым запустится контейнер
    hostname: devops_exam_db #Имя "хоста" которым будет считать себя контейнер
    image: mysql:latest #Образ из которого запускается контейнер
    volumes: #Подключаемые директории
      - dbdata:/var/lib/mysql #Директории вида хост_директория:директория_контейнера
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment: #переменные окружения
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: admin
      MYSQL_HOST: devops_exam_db
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: devops_exam_db
    ports: # Сопоставление портов хост-машины и контейнера
      - 3307:3307
    restart: unless-stopped #условие для рестарта в случае остановки контейнера

  devops_exam_app:
    container_name: devops_exam_app
    hostname: devops_exam_app
    image: lavlinsky2402/devops_exam:latest
    build: # Параметры для сборки приложения
      context: ./ # Каталог, используемый для сборки
      dockerfile: Dockerfile # Файл, используемый для сборки образа приложения
    ports:
     - 10091:80
    # networks:
    #   - devops_exam-net
    restart: unless-stopped
    depends_on: # Указание на зависимость сервиса от другого сервиса
      - devops_exam_db

# networks:
#   devops_exam-net:

volumes:
  dbdata:
